config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "profile", to: "pages#profile"
  get "privacy", to: "pages#privacy"
  resources "itineraries", only: %i[index show create update] do
    resources "bookmarks", only: %i[create destroy]
    resources "trips", only: :create
  end
  resources "trips", only: %i[show create update] do
    resources "questions", only: :index do
      resources "itineraries", only: %i[update]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :itinerary
end

app/models/city.rb
class City < ApplicationRecord
  has_many :itineraries
  # validates :name, presence: true, uniqueness: true
end

app/models/itinerary.rb
class Itinerary < ApplicationRecord
  belongs_to :city
  has_many :itinerary_pois, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :pois, through: :itinerary_pois
  has_many :trips
  has_many :bookmarks
  has_many :users, through: :bookmarks
  has_many_attached :photos
  geocoded_by :departure

  attribute :rates, :integer, default: [], array: true

  after_validation :geocode, if: :will_save_change_to_departure?
end

app/models/itinerary_poi.rb
class ItineraryPoi < ApplicationRecord
  belongs_to :itinerary
  belongs_to :poi
end

app/models/poi.rb
class Poi < ApplicationRecord
  has_many :itinerary_pois, dependent: :destroy
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :itinerary
  has_many :trips, through: :itineraries
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user
  has_many :questions, through: :itineraries
  belongs_to :itinerary
  geocoded_by :departure
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  has_many :trips, dependent: :destroy
  has_many :bookmarks
  has_many :itineraries, through: :bookmarks

  validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/ }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_itinerary

  def create
    @bookmark = Bookmark.new(user: current_user, itinerary: @itinerary, favorite: true)

    if @bookmark.save
      respond_to do |format|
        format.turbo_stream { redirect_to @itinerary, notice: 'Ajouté aux favoris :-)' }
        format.js
      end
    else
      render itinerary_path(@itinerary)
    end
  end

  def destroy
    @bookmark = Bookmark.find_by(user: current_user, itinerary: @itinerary)
    @bookmark.destroy
    respond_to do |format|
      format.turbo_stream { redirect_to @itinerary, notice: 'Retiré des favoris :-(' }
      format.js
    end
  end

  private

  def set_itinerary
    @itinerary = Itinerary.find(params[:itinerary_id])
  end
end

app/controllers/itineraries_controller.rb
class ItinerariesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    if params[:query].present?
      city = City.where("to_tsvector('english', name) @@ plainto_tsquery('english', ?)", params[:query].to_s)
      @itineraries = Itinerary.where(city_id: city.ids[0].to_i)
      @itineraries = @itineraries.merge(Itinerary.where(category: params[:category])) if params[:category].present?
    else
      @itineraries = Itinerary.all
    end
    @itineraries_markers = @itineraries.geocoded.map do |itinerary|
      {
        lat: itinerary.latitude,
        lng: itinerary.longitude,
        completed: itinerary.trips.where(user: current_user).any?(&:completed?),
        name: itinerary.name
      }
    end
  end

  def short(itineraries)
    itineraries.where("duration < 90")
  end

  def long(itineraries)
    itineraries.where("duration >= 90")
  end

  def show
    @itinerary = Itinerary.find(params[:id])
    if Trip.exists?(user: current_user, itinerary: @itinerary, completed: false)
      @trip = Trip.find_by(user: current_user, itinerary: @itinerary, completed: false)
    else
      @trip = Trip.new
    end
    @bookmarks = Bookmark.where(user: current_user, itinerary: @itinerary)
    @markers = { lat: @itinerary.latitude, lng: @itinerary.longitude }
  end

  def update
    @itinerary = Itinerary.find(params[:id])
    new_rate = params[:itinerary][:rates].to_i
    @itinerary.rates << new_rate
    flash[:notice] = "Merci pour votre note !" if @itinerary.save
    redirect_to itineraries_path
  end

  def rating(itinerary)
    (itinerary.rates.sum / itinerary.rates.length).truncate(0)
  end

  helper_method :rating, :short, :long

  private

  def itinerary_params
    params.require(:itinerary).permit(:rates)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[home privacy]

  def home
  end

  def profile
    user_trips = Trip.where(user_id: current_user.id, completed: true)
    @completed_itineraries = user_trips.map(&:itinerary)
    bookmarks = Bookmark.where(user_id: current_user.id, favorite: true)
    @favorite_itineraries = bookmarks.map(&:itinerary)
  end

  def privacy
  end

  def rating(itinerary)
    (itinerary.rates.sum / itinerary.rates.length).truncate(0)
  end

  helper_method :rating
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @trip = Trip.find(params[:trip_id])
    @questions = Question.where(itinerary_id: @trip.itinerary)
    @itinerary = @trip.itinerary
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  def show
    @trip = Trip.find(params[:id])
    @itinerary = @trip.itinerary
    @pois = @itinerary.pois
    @departure = @itinerary.departure
    @markers = @pois.geocoded.map do |poi|
      { lat: poi.latitude, lng: poi.longitude }
    end
    @departure_marker = [{ lat: @itinerary.latitude, lng: @itinerary.longitude }]
  end

  def create
    @itinerary = Itinerary.find(params[:itinerary_id])
    @trip = Trip.new
    @trip.user = current_user
    @trip.itinerary = @itinerary
    if @trip.save!
      redirect_to trip_path(@trip)
    else
      render itinerary_path(@itinerary), status: :unprocessable_entity
    end
  end

  def update
    @trip = Trip.find(params[:id])
    @trip.update(trip_params)
    redirect_to trip_questions_path(@trip)
  end

  private

  def trip_params
    params.require(:trip).permit(:proximity_level, :image, :content, :status, :progress, :departure, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/itineraries/_bookmark.html.erb
<% if @itinerary.bookmarks.empty? %>
  <div data-controller="bookmark">
    <%= form_with(url: itinerary_bookmarks_path(@itinerary), method: :post, local: true, data: { bookmark_target: "form" }) do |f| %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.hidden_field :itinerary_id, value: @itinerary.id %>
      <%= f.hidden_field :completed, value: true %>
      <button class="button-favorite" data-action="click->bookmark#submit" data-bookmark-target="button">
        <i class="fa-regular fa-heart"></i>
      </button>
    <% end %>
  </div>
<% else %>
  <div data-controller="bookmark">
    <%= form_with(url: itinerary_bookmark_path(@itinerary), method: :delete, local: true, data: { bookmark_target: "form" }) do |f| %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.hidden_field :itinerary_id, value: @itinerary.id %>
      <button class="button-favorite button-favorite-active" data-action="click->bookmark#submit" data-bookmark-target="button">
        <i class="fa-regular fa-heart"></i>
      </button>
    <% end %>
  </div>
<% end %>

app/views/itineraries/_itineraries_list.html.erb
<div class="cards-wrapper">
  <div class="d-flex cards">
    <% itineraries.each do |itinerary| %>
      <div class="card" data-switch-target="<%= itinerary.category %>" data-filter="<%= itinerary.category %>">
        <%= link_to itinerary_path(itinerary) do %>
          <div class="card-img position-relative">
            <%= cl_image_tag itinerary.photos.first.key, height: 160, width: 285, crop: :fill %>
            <div class="card-details">
              <div class="card-show-itinerary-infos text-small card-index-details">
                <div><%= image_tag "steps.svg" %> <%= itinerary.distance %> km</div>
                <div><%= image_tag "hourglass.svg" %> <%= itinerary.duration / 60 %> h <%=  itinerary.duration % 60 if itinerary.duration % 60 != 0 %></div>
              </div>
              <div>
                <% rating(itinerary).times do |i| %>
                  <%= image_tag "star.svg" %>
                <% end %>
                <% (5 - rating(itinerary)).times do |i| %>
                  <%= image_tag "emptystar.svg" %>
                <% end %>
              </div>
            </div>
          </div>
          <div class="card-infos">
            <h4><%= itinerary.name %></h4>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/itineraries/index.html.erb
<div data-controller="switch">
  <%# Navbar %>
  <%= render 'shared/navbar' %>
  <%# List Results %>
  <div data-switch-target="list" class="d-flex flex-column container-index overflow-hidden">
    <div>
      <div class="d-flex justify-content-between">
        <h2>
          <% if params[:query].present? %>
            Tous les itinéraires
            <br><%= "à #{params[:query]}" %>
          <% else %>
            Tous les itinéraires
          <% end %>
        </h2>
        <%# Insérer le symbol des filtres qui fait apparaître la modal %>
      </div>
      <div class="d-flex justify-content-between checkbox-wrapper">
        <div data-action="click->switch#filter" data-switch-target="btnAucun"
             data-filter="Aucun" class="btn btn-filter btn-primary">Aucun</div>
        <div data-action="click->switch#filter" data-switch-target="btnNature"
             data-filter="Nature" class="btn btn-filter btn-outline-primary">Nature</div>
        <div data-action="click->switch#filter" data-switch-target="btnUrbain"
             data-filter="Urbain" class="btn btn-filter btn-outline-primary">Urbain</div>
        <div data-action="click->switch#filter" data-switch-target="btnMedieval"
             data-filter="Médiéval" class="btn btn-filter btn-outline-primary">Médiéval</div>
        <div data-action="click->switch#filter" data-switch-target="btnPrehistorique"
             data-filter="Préhistorique" class="btn btn-filter btn-outline-primary">Préhistorique</div>
      </div>
    </div>

    <%# Cards %>
    <div>
      <h3>Proches de vous</h3>
      <%= render 'itineraries_list', itineraries: @itineraries %>
    </div>
    <div>
      <h3>Balade rapide</h3>
      <%= render 'itineraries_list', itineraries: short(@itineraries) %>
    </div>
    <div>
      <h3>Grands marcheurs</h3>
      <%= render 'itineraries_list', itineraries: long(@itineraries) %>
    </div>
  </div>

  <%# Cards on Map %>
  <div class="cards-wrapper cards-fixed d-none" data-switch-target="cardsForMap">
    <div class="d-flex cards">
      <% @itineraries.each do |itinerary| %>
        <div class="card card-reduce">
          <%= link_to itinerary_path(itinerary), class:'d-flex align-items-center' do %>
            <%= cl_image_tag itinerary.photos.first.key, height: 110, width: 100, crop: :fill %>
            <div class="card-infos">
              <div>
                <% rating(itinerary).times do |i| %>
                  <%= image_tag "star.svg" %>
                <% end %>
                <% (5 - rating(itinerary)).times do |i| %>
                  <%= image_tag "emptystar.svg" %>
                <% end %>
              </div>
              <h4 id="card-name-map"><%= itinerary.name %></h4>
              <div class="card-details">
                <div class="card-show-itinerary-infos align-items-center text-small card-index-details">
                  <%= image_tag "steps.svg" %> <%= itinerary.distance %> km
                  <%= image_tag "hourglass.svg" %> <%= itinerary.duration / 60 %> h <%=  itinerary.duration % 60 if itinerary.duration % 60 != 0 %>
                </div>
              </div>
              <span class="itinerary-infos d-none"><%= itinerary.latitude %></span>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

  <%# Map %>
  <div class="position-relative wrapper-map map-hidden" data-switch-target="wrapperMap">
    <div class="map-overlay"></div>
    <div  id="itinerary-map"
          class="opacity-0"
          data-switch-target="map"
          data-controller="itineraries"
          data-itineraries-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
          data-itineraries-markers-value="<%= @itineraries_markers.to_json %>">
    </div>
  </div>
</div>

app/views/itineraries/show.html.erb
<div class= "main_show_div">
  <div class= "card_show_itinerary" >
    <%= cl_image_tag @itinerary.photos.first.key, class: "show-image", crop: :fill %>
    <%= link_to "javascript:history.back()", class: "button-return" do %>
      <i class="fa-solid fa-chevron-left"></i>
      <span>RETOUR</span>
    <% end %>
    <% if user_signed_in? %>
      <%= render 'bookmark' %>
    <% end %>
  </div>
  <div class="banner-show">
    <h2><%= @itinerary.name %></h2>
  </div>
  <div class="card_show_itinerary_content">
    <div class="rating-stars">
      <% rating(@itinerary).times do |i| %>
        <%= image_tag "star.svg" %>
      <% end %>
      <% (5 - rating(@itinerary)).times do |i| %>
        <%= image_tag "emptystar.svg" %>
      <% end %>
    </div>
    <div class="card-show-itinerary-infos text-small d-flex flex-row justify-content-between gap-infos">
      <div><%= image_tag "steps.svg" %> <%= @itinerary.distance %> km</div>
      <div><%= image_tag "hourglass.svg" %> <%= @itinerary.duration / 60 %> h <%=  @itinerary.duration % 60 if @itinerary.duration % 60 != 0 %></div>
    </div>
  </div>
  <div class="card_show_description">
    <p class="big-size"><i> <%= @itinerary.subtitle %></i></p>
    <p><%= @itinerary.description %></p>
  </div>
  <div class="card_show_bottom">
    <% if user_signed_in? %>
      <% if Trip.exists?(user: current_user, itinerary: @itinerary, completed: false) %>
        <%= link_to "Reprendre l'itinéraire", trip_path(@trip), class: "btn btn-primary w-100" %>
      <% else %>
        <%= simple_form_for [@itinerary, @trip] do |f| %>
          <%= f.submit "Allons-y", class: "btn btn-primary w-100" %>
        <% end %>
      <% end %>
    <% else %>
      <%= link_to "Se connecter pour aller plus loin", new_user_session_path, class: "btn btn-primary w-100" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BreizhSecrets</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    <meta name="viewport" content="initial-scale=1,maximum-scale=1,user-scalable=no">
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.13.0/mapbox-gl.css" rel="stylesheet"> <%# maybe to delete %>
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.13.0/mapbox-gl.js"></script>
    <style>
      body { margin: 0; padding: 0; }
      #map { position: absolute; top: 0; bottom: 0; width: 100%; }
    </style> <%# maybe to delete %>
    <script src="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-directions/v4.1.1/mapbox-gl-directions.js"></script>
    <link rel="stylesheet" href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-directions/v4.1.1/mapbox-gl-directions.css" type="text/css">
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <script src="https://unpkg.com/@turf/turf@6/turf.min.js"></script>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
    <%= render 'shared/ios_pwa_links' %>
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
  </head>

  <body class="background-color">
    <div class="container-device">
      <%= render "shared/flashes" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/_itineraries_list.html.erb
<% itineraries.each do |itinerary| %>
  <div data-account-target="itinerariesList" class="card card-profile">
    <%= link_to itinerary_path(itinerary), class:'d-flex align-items-center' do %>
      <%= cl_image_tag itinerary.photos.first.key, height: 110, width: 100, crop: :fill %>
      <div class="card-infos">
        <div>
          <% rating(itinerary).times do |i| %>
            <%= image_tag "star.svg" %>
          <% end %>
          <% (5 - rating(itinerary)).times do |i| %>
            <%= image_tag "emptystar.svg" %>
          <% end %>
        </div>
        <h4><%= itinerary.name %></h4>
        <div class="card-details">
          <div class="card-show-itinerary-infos align-items-center text-small card-index-details">
            <%= image_tag "steps.svg" %> <%= itinerary.distance %> km
            <%= image_tag "hourglass.svg" %> <%= itinerary.duration / 60 %> h <%=  itinerary.duration % 60 if itinerary.duration % 60 != 0 %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/pages/home.html.erb
<div id="desktop-warning" style="display: none; position: fixed; top: 0; left: 0; width: 100%; height: 100%; background-color: rgba(0,0,0,0.7); color: white; z-index: 9999; text-align: center; padding-top: 20%;">
  <h1>Désolé, cette application est optimisée pour un usage sur smartphone.</h1>
  <p>Merci de rejoindre notre application sur votre mobile.</p>
</div>

<div class="position-relative wrapper-home">
  <video class="position-absolute video" autoplay loop muted playsinline>
    <source src="<%= asset_path 'bretagne.mp4' %>" type="video/mp4">
  </video>
  <div class="position-absolute filter"></div>
  <div class="position-absolute wrapper-content">
    <h1 class='title'>Découvrez les secrets de la Bretagne</h1>
    <div class="rotating-text-wrapper">
      <p>Revivez l'histoire en parcourant les terres de Bretagne</p>
      <p>Voyagez à travers les nombreux secrets qui ont fait la légende de ce territoire</p>
      <p>Marchez sur les traces des anciens Bretons et plongez dans l'histoire fascinante de cette région</p>
    </div>
    <div class='form'>
      <%= form_with url: itineraries_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control form-radius",
          placeholder: "Chercher par localisation"
        %>
        <%= image_submit_tag("search.svg", alt: "Rechercher", class: "btn form-btn btn-primary") %>
      <% end %>
    </div>

    <%= link_to "Découvrir des itinéraires", itineraries_path, class:'btn btn-primary' %>
  </div>
</div>


<script>
  window.addEventListener("load", function() {
    if (window.innerWidth > 450) {
      document.getElementById('desktop-warning').style.display = 'block';
    }
  });
</script>

app/views/pages/profile.html.erb
<div data-controller='account' class="d-flex flex-column container-profile">
  <div class='d-flex flex-row justify-content-between align-items-center'>
    <h1>Votre profil</h1>
    <i class="fa-solid fa-gear" data-account-target="gear" data-action="click->account#appearOptions"></i>
    <i class="fa-solid fa-xmark d-none" data-account-target="cross" data-action="click->account#disappearOptions"></i>
  </div>
  <h2 data-account-target="itinerariesCategory" style="margin-top: 10px; margin-bottom: 0px">
    Vos itinéraires favoris
  </h2>
  <%= render 'itineraries_list', itineraries: @favorite_itineraries %>
  <h2 data-account-target="itinerariesCategory" style="margin-top: 10px; margin-bottom: 0px">
    Itinéraires faits
  </h2>
  <%= render 'itineraries_list', itineraries: @completed_itineraries %>
  <%=
    link_to 'Retour aux itinéraires', itineraries_path,
    data: {account_target: "backButton"},
    class: 'btn btn-primary btn-center'
  %>
  <%=
    link_to "Politiques de confidentialité", privacy_path,
    data: {account_target: "privacyButton"},
    class: 'btn btn-primary d-none'
  %>
  <%=
    link_to "Déconnexion", destroy_user_session_path,
    data: {account_target: "logoutButton", turbo_method: :delete},
    class: 'btn btn-primary d-none'
  %>
  <%=
    link_to 'Supprimer mon compte', user_registration_path,
    data: {account_target: "deleteButton", turbo_method: :delete, turbo_confirm: "Êtes vous sûr(e) ?"},
    class: "btn btn-primary btn-center d-none"
  %>
</div>

app/views/questions/_congratulations.html.erb
<div class="d-flex flex-wrap justify-content-center">
    <div data-questions-target="congratulation" class="wrapper-congratulation d-none d-flex flex-column justify-content-center mt-15">
      <h2 class="question-center">Félicitations ! A bientôt pour de nouvelles aventures !</h2>
      <%= cl_image_tag @trip.itinerary.photos.first.key, class: 'quizz-image', crop: :fill %>
      <div class="wrapper-rating">
        <h4 class="question-center">Ajouter une note</h4>
        <%= simple_form_for(@itinerary) do |f| %>
          <div class="star-rating" data-controller='rating'>
            <% (1..5).each do |value| %>
              <%= label_tag "rating_#{value}", class: 'star',
                  data: { action: "click->rating#updateStars" } do %>
                <%= image_tag 'emptystar.svg', data: { rate: value, rating_target: "emptyStar" } %>
                <%= image_tag 'star.svg', class: 'd-none', data: { rate: value, rating_target: "star" } %>
              <% end %>
              <%= f.radio_button :rates, value, id: "rating_#{value}", class: 'star-input visually-hidden' %>
            <% end %>
          </div>
          <%= f.submit "Valider", class: 'btn btn-primary' %>
        <% end %>
      </div>
      <%= link_to 'Retourner aux itinéraires', itineraries_path, class: 'btn btn-primary btn-center' %>
    </div>
  </div>

app/views/questions/_quizz.html.erb
<% @trip.itinerary.questions.each_with_index do |question, index| %>
  <div class="d-flex flex-column question-index d-none" data-questions-target="question">
    <div>
      <%= cl_image_tag @trip.itinerary.photos.first.key, class: 'question-img', crop: :fill %>
    </div>
    <div class="d-flex flex-column">
      <h2 class="d-flex justify-content-center mb-0">Question <%= index + 1 %></h2>
      <p class="text-center mb-0"><%= question.question_statement %></p>
    </div>
    <div class="d-flex flex-wrap justify-content-center questions-wrapper">
      <% question.answer_statement.each do |answer|  %>
        <% if answer == question.good_answer && index == @trip.itinerary.questions.length - 1 %>
          <div class='btn btn-outline-primary btn-question m-1'
               data-action='click->questions#goodAnswer click->questions#confettis'>
            <%= answer %>
          </div>
        <% elsif answer == question.good_answer %>
          <div class='btn btn-outline-primary btn-question m-1' data-action='click->questions#goodAnswer'>
            <%= answer %>
          </div>
        <% else %>
          <div class='btn btn-outline-primary btn-question m-1' data-questions-target='badAnswer'
               data-action='click->questions#badAnswer'>
            <%= answer %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/questions/index.html.erb
<div class="d-flex flex-column quizz-wrapper align-items-center" data-controller="questions">
  <h2><strong><%= @itinerary.quiz_name %></strong></h2>
  <div class='background-progress'>
    <div data-questions-target="progress" class="progress-bar">
    </div>
  </div>
  <%= render 'quizz' %>
  <%= render 'congratulations' %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="position-relative">
  <div class="d-flex justify-content-between phone-navbar align-items-center">
    <div class="navbar-item">
      <%= link_to root_path do %>
        <%= image_tag('navbar/home.svg') %>
      <% end %>
      <p>Accueil</p>
    </div>
    <div class="navbar-item navbar-icon" data-action="click->switch#displayList" data-switch-target="my-anchor svglist">
      <%= image_tag('navbar/list.svg') %>
      <p>Liste</p>
    </div>
    <div class="navbar-item"  data-action="click->switch#displayMap" data-switch-target="my-anchor svgmap">
      <%= image_tag('navbar/map.svg') %>
      <p>Carte</p>
    </div>
    <div class="navbar-item">
      <%= link_to profile_path do %>
        <%= image_tag('navbar/profil.svg') %>
        <p>Profil</p>
      <% end %>
    </div>
    <div class="dropdown-menu doprdown-menu-end" aria-labelledby="navbarDropdown">
      <%= link_to "Historiques", class: "dropdown-item" %>
      <%= link_to "Favoris", class: "dropdown-item" %>
      <%= link_to "Parcours Sauvegardé", class: "dropdown-item" %>
      <%= link_to "Déconnexion", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
    </div>
  </div>
</div>

app/views/trips/_fake_trip.html.erb
<div class="position-absolute" style="width: 100vw; height: 100vh;"
  data-controller="fake-trip-map"
  data-custom-marker="<%= asset_path('ghost.png') %>"
  data-fake-trip-map-markers-value="<%= @markers.to_json %>"
  data-fake-trip-map-departure-markers-value="<%= @departure_marker.to_json %>"
  data-fake-trip-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

app/views/trips/_real_trip.html.erb
<div class="position-absolute" style="width: 100vw; height: 100vh;"
  data-controller="real-trip-map"
  data-real-trip-map-markers-value="<%= @markers.to_json %>"
  data-real-trip-map-departure-markers-value="<%= @departure_marker.to_json %>"
  data-real-trip-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>